# Generated by Django 2.2.3 on 2020-12-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_image', models.ImageField(upload_to='uploads/advertising/')),
                ('advertising_start_date', models.DateField()),
                ('advertising_end_date', models.DateField()),
                ('advertising_message', models.CharField(max_length=200)),
                ('store_id', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Shop_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgfrom', models.CharField(max_length=50)),
                ('msgto', models.CharField(max_length=50)),
                ('msgfromusertype', models.CharField(max_length=50)),
                ('msgtusertype', models.CharField(max_length=50)),
                ('msgtime', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('driver_image', models.ImageField(upload_to='uploads/driver/')),
                ('password', models.CharField(max_length=500)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(default='', max_length=50)),
                ('address1', models.CharField(default='', max_length=200)),
                ('apt', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('vehical_type', models.CharField(default='', max_length=100)),
                ('social_security', models.CharField(default='', max_length=200)),
                ('license_number', models.CharField(default='', max_length=200)),
                ('islicense', models.CharField(default='', max_length=100)),
                ('account_number', models.CharField(default='', max_length=100)),
                ('routing_number', models.CharField(default='', max_length=100)),
                ('convicted_of_any_felonies', models.CharField(default='', max_length=100)),
                ('concede_to_a_background_check', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('user', models.IntegerField()),
                ('like', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=500)),
                ('notification_to', models.IntegerField()),
                ('notification_from_type', models.CharField(max_length=100)),
                ('notification_time', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
                ('otpcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('product_category', models.CharField(max_length=50)),
                ('product_descriptions', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='uploads/products/')),
                ('store_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profilepicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='uploads/store/71doo5dci8L._SL1200__flBZ8kI.jpg', upload_to='uploads/userimages/')),
                ('user_type', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Shopcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_image', models.ImageField(default='uploads/store/71doo5dci8L._SL1200__flBZ8kI.jpg', upload_to='uploads/store/')),
                ('store_password', models.CharField(max_length=500)),
                ('store_open_date', models.DateField()),
                ('store_category', models.IntegerField()),
                ('store_address', models.CharField(default='', max_length=200)),
                ('store_suit', models.CharField(default='', max_length=200)),
                ('store_city', models.CharField(default='', max_length=200)),
                ('store_state', models.CharField(default='', max_length=200)),
                ('store_phone', models.CharField(default='', max_length=20)),
                ('store_zipcode', models.CharField(default='', max_length=50)),
                ('store_tax', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('store_delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('store_aggrement', models.CharField(default='', max_length=50)),
                ('store_active', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cat_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user_image', models.ImageField(default='uploads/store/71doo5dci8L._SL1200__flBZ8kI.jpg', upload_to='uploads/store/')),
                ('password', models.CharField(max_length=500)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('mailaddress1', models.CharField(default='', max_length=200)),
                ('mailaddress2', models.CharField(default='', max_length=200)),
                ('mailcity', models.CharField(default='', max_length=100)),
                ('mailstate', models.CharField(default='', max_length=100)),
                ('mailzipcode', models.CharField(default='', max_length=100)),
                ('mailphone_number', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('mailing_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(default='', max_length=200)),
                ('card_number', models.CharField(default='', max_length=200)),
                ('security_code', models.CharField(default='', max_length=100)),
                ('expiration_date', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('stripe_charge_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('orderpickup', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Driverorderpickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
    ]
