# Generated by Django 2.2 on 2020-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_image', models.ImageField(upload_to='uploads/store/')),
                ('store_identification_number', models.CharField(default='', max_length=100)),
                ('store_password', models.CharField(max_length=500)),
                ('store_open_date', models.DateField()),
                ('store_address', models.CharField(default='', max_length=200)),
                ('store_suit', models.CharField(default='', max_length=200)),
                ('store_city', models.CharField(default='', max_length=200)),
                ('store_state', models.CharField(default='', max_length=200)),
                ('store_phone', models.CharField(default='', max_length=20)),
                ('store_zipcode', models.CharField(default='', max_length=50)),
                ('store_aggrement', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
