# Generated by Django 2.2 on 2020-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_image', models.ImageField(upload_to='uploads/advertising/')),
                ('advertising_start_date', models.DateField()),
                ('advertising_end_date', models.DateField()),
                ('advertising_message', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('root', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(default=0)),
                ('product_category', models.CharField(max_length=50)),
                ('product_descriptions', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='uploads/products/')),
                ('store_id', models.IntegerField(default=0)),
            ],
        ),
    ]
