# Generated by Django 2.2 on 2020-11-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_advertising_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_identification_number',
        ),
    ]
