# Generated by Django 2.2 on 2020-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_store_store_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='root',
        ),
        migrations.AddField(
            model_name='category',
            name='Shop_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
