# Generated by Django 2.2 on 2020-11-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='store_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
