# Generated by Django 2.2 on 2020-11-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201127_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
