# Generated by Django 2.2 on 2020-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='concede_to_a_background_check',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='convicted_of_any_felonies',
            field=models.CharField(default='', max_length=100),
        ),
    ]
