# Generated by Django 2.2 on 2020-11-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201128_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderpickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehical_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
