# Generated by Django 2.2 on 2020-12-02 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_from_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
