# Generated by Django 2.2 on 2020-12-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20201202_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(default='uploads/store/71doo5dci8L._SL1200__flBZ8kI.jpg', upload_to='uploads/store/'),
        ),
    ]
