# Generated by Django 2.2 on 2020-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20201203_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='uploads/store/71doo5dci8L._SL1200__flBZ8kI.jpg', upload_to='uploads/store/'),
        ),
    ]
