# Generated by Django 2.2.3 on 2020-12-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20201210_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgfrom', models.CharField(max_length=50)),
                ('msgto', models.CharField(max_length=50)),
                ('msgfromusertype', models.CharField(max_length=50)),
                ('msgtusertype', models.CharField(max_length=50)),
                ('msgtime', models.CharField(max_length=50)),
            ],
        ),
    ]
