# Generated by Django 2.2.3 on 2020-12-10 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='msg',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
