# Generated by Django 2.2.3 on 2020-12-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_chat_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
                ('otpcode', models.CharField(max_length=10)),
            ],
        ),
    ]
