# Generated by Django 2.2.3 on 2020-12-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_active',
            field=models.IntegerField(default=0),
        ),
    ]
