# Generated by Django 2.2.3 on 2020-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_delivery_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='store',
            name='store_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
