# Generated by Django 2.2.3 on 2020-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20201226_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(default='', max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('coupon_status', models.IntegerField(default=1)),
            ],
        ),
    ]
