# Generated by Django 2.2.3 on 2020-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_store_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
