# Generated by Django 2.2.3 on 2020-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_coupon_coupon_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productfilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=100)),
                ('filter_category', models.IntegerField()),
                ('filter_store_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
